# PyTorch Tensor

In [1]:
import torch
import numpy as np

In [2]:
data = [
    [1, 2],
    [3, 4]
]

tensor_data = torch.tensor(data)
np_data = np.array(data)

In [3]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_data

array([[1, 2],
       [3, 4]])

In [5]:
tensor_data_from_np = torch.from_numpy(np_data)

In [7]:
tensor_data_from_np == tensor_data

tensor([[True, True],
        [True, True]])

In [8]:
tensor_data == np_data

False

In [14]:
tensor_ones = torch.ones([4, 4])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
tensor_ones = torch.ones_like(tensor_data)
tensor_ones

tensor([[1, 1],
        [1, 1]])

In [16]:
shape = (2, 3, )
tensor_rand = torch.rand(shape)
tensor_rand

tensor([[0.6594, 0.2426, 0.0689],
        [0.0197, 0.0817, 0.2413]])

In [17]:
tensor_data.device

device(type='cpu')

In [18]:
tensor_data.shape

torch.Size([2, 2])

In [19]:
tensor_data.dtype


torch.int64

In [24]:
tensor = torch.range(1, 9).reshape(3, 3)
tensor

/var/folders/px/w0rlccd16q5frb31swtpv1200000gn/T/ipykernel_88532/2976639397.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor = torch.range(1, 9).reshape(3, 3)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [25]:
tensor[0]

tensor([1., 2., 3.])

In [26]:
tensor[:, 0]

tensor([1., 4., 7.])

In [29]:
tensor[..., -1]

tensor([3., 6., 9.])

In [30]:
tensor @ tensor.T

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])

In [31]:
tensor * tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])